export const MOVIES_GET_START = 'app/Home/MOVIES_GET_START';
export const MOVIES_GET_START_ASYNC = 'app/Home/MOVIES_GET_START_ASYNC';
export const MOVIES_GET_SUCCESS = 'app/Home/MOVIES_GET_SUCCESS';

export const MOVIES_SEARCH_START = 'app/Home/MOVIES_SEARCH_START';
export const MOVIES_SEARCH_START_ASYNC = 'app/Home/MOVIES_SEARCH_START_ASYNC';
export const MOVIES_SEARCH_SUCCESS = 'app/Home/MOVIES_SEARCH_SUCCESS';

export const MOVIES_SET_ERROR = 'app/Home/MOVIES_SET_ERROR';

